apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # These values should be base64 encoded
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bwb3N0Z3Jlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZGI=
  broker-url: YW1xcDovL3VzZXI6cGFzc0ByYWJiaXRtcS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzIv
  openai-api-key: eW91ci1hcGkta2V5LWhlcmU=
  discord-token: eW91ci1kaXNjb3JkLXRva2VuLWhlcmU=
